import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as iam from 'aws-cdk-lib/aws-iam';

/**
 * Static-site hosting for the JetBrains AI cheat sheets:
 *   - private S3 bucket (no public access)
 *   - CloudFront distribution with Origin Access Control + HTTPS
 *   - a GitHub OIDC-assumable IAM role scoped to s3 sync + CloudFront invalidation
 *
 * Optional custom domain via context: `domainName`, `certificateArn`
 * (an ACM cert in us-east-1). Optional reuse of an existing GitHub OIDC
 * provider via context `existingOidcProviderArn`.
 */
export class CheatsheetsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const githubRepo = this.node.tryGetContext('githubRepo') as string;
    const githubBranch = (this.node.tryGetContext('githubBranch') as string) ?? 'main';
    if (!githubRepo || !githubRepo.includes('/')) {
      throw new Error('Set context "githubRepo" to "owner/repo" (see cdk.json).');
    }

    const domainName = this.node.tryGetContext('domainName') as string | undefined;
    const certificateArn = this.node.tryGetContext('certificateArn') as string | undefined;

    // --- Private origin bucket -------------------------------------------------
    const bucket = new s3.Bucket(this, 'SiteBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      // The site is regenerated by CI on every run; safe to recreate.
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    // --- CloudFront distribution (OAC + HTTPS) ---------------------------------
    const certificate =
      domainName && certificateArn
        ? cdk.aws_certificatemanager.Certificate.fromCertificateArn(this, 'Cert', certificateArn)
        : undefined;

    const distribution = new cloudfront.Distribution(this, 'Distribution', {
      defaultRootObject: 'index.html',
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      domainNames: domainName ? [domainName] : undefined,
      certificate,
      priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
      comment: 'JetBrains AI cheat sheets',
    });

    // --- GitHub OIDC role for CI deploys ---------------------------------------
    const existingOidcProviderArn = this.node.tryGetContext('existingOidcProviderArn') as
      | string
      | undefined;

    const oidcProvider = existingOidcProviderArn
      ? iam.OpenIdConnectProvider.fromOpenIdConnectProviderArn(
          this,
          'GithubOidc',
          existingOidcProviderArn,
        )
      : new iam.OpenIdConnectProvider(this, 'GithubOidc', {
          url: 'https://token.actions.githubusercontent.com',
          clientIds: ['sts.amazonaws.com'],
        });

    const deployRole = new iam.Role(this, 'CiDeployRole', {
      roleName: 'jetbrains-ai-cheatsheets-ci-deploy',
      assumedBy: new iam.OpenIdConnectPrincipal(oidcProvider, {
        StringEquals: {
          'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com',
        },
        StringLike: {
          // Restrict to this repo's chosen branch (and workflow_dispatch on it).
          'token.actions.githubusercontent.com:sub': `repo:${githubRepo}:ref:refs/heads/${githubBranch}`,
        },
      }),
      description: 'Assumed by GitHub Actions (OIDC) to publish the cheat-sheet site',
      maxSessionDuration: cdk.Duration.hours(1),
    });

    bucket.grantReadWrite(deployRole);
    deployRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['cloudfront:CreateInvalidation', 'cloudfront:GetInvalidation'],
        resources: [
          cdk.Stack.of(this).formatArn({
            service: 'cloudfront',
            region: '',
            resource: 'distribution',
            resourceName: distribution.distributionId,
          }),
        ],
      }),
    );

    // --- Outputs (feed these into GitHub Actions vars) -------------------------
    new cdk.CfnOutput(this, 'BucketName', { value: bucket.bucketName });
    new cdk.CfnOutput(this, 'DistributionId', { value: distribution.distributionId });
    new cdk.CfnOutput(this, 'DistributionDomain', {
      value: `https://${distribution.distributionDomainName}`,
    });
    new cdk.CfnOutput(this, 'CiDeployRoleArn', { value: deployRole.roleArn });
    if (domainName) {
      new cdk.CfnOutput(this, 'CustomDomain', { value: `https://${domainName}` });
    }
  }
}
